# Generated by Django 4.2 on 2023-05-03 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shophagi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='decent',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='shophagi.decentralization'),
        ),
    ]
